'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9035
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GetTixApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _001_3d_glasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_001_3d_glasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _001_popcorn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001-popcorn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _002_video_camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("002-video-camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _003_film() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("003-film", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _004_cinema() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("004-cinema", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _005_video_cameras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("005-video-cameras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _030_popcorn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_030_popcorn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _039_theatre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_039_theatre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calendar_Day() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar-Day", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Film_Projector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Film-Projector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Film_Strip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Film-Strip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flat_landscape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flat-landscape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property landscape_1280x720_flat_4k_5k_fog_iphone_wallpaper_forest_blue_11927() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("landscape-1280x720-flat-4k-5k-fog-iphone-wallpaper-forest-blue-11927", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property No_Image_Available() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No-Image-Available", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property POSTER_movie_film_movies_posters_5120x3620() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("POSTER_movie_film_movies_posters_5120x3620", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property power_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power-off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property power_off__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power-off (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Projection_Room() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Projection-Room", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_576228_1280() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket-576228_1280", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ticket_576228_640() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ticket-576228_640", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
